//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_network
    {
        public int id { get; set; }
        public string serial_number { get; set; }
        public string name { get; set; }
        public Nullable<int> ports_count { get; set; }
        public string transfer_standart { get; set; }
        public Nullable<double> frequency { get; set; }
        public string interfaces { get; set; }
        public string transfer_speed { get; set; }
        public string location { get; set; }
    }
}
