//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicaitons
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> subscriber { get; set; }
        public string service { get; set; }
        public string service_kind { get; set; }
        public string serivce_type { get; set; }
        public string status { get; set; }
        public string problem_description { get; set; }
        public string problem_type { get; set; }
    
        public virtual subscribers subscribers { get; set; }
    }
}
