//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class backbone_equipment
    {
        public int id { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public Nullable<double> frequency { get; set; }
        public Nullable<double> damping_factor { get; set; }
        public string transfer_technology { get; set; }
        public string location { get; set; }
    }
}
