//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_for_employeers
    {
        public int id { get; set; }
        public Nullable<int> employee_role { get; set; }
        public string message { get; set; }
        public string status { get; set; }
    
        public virtual employee_roles employee_roles { get; set; }
    }
}
