//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPEntities : DbContext
    {
        public UPEntities()
            : base("name=UPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<completed_applications> completed_applications { get; set; }
        public virtual DbSet<job_title> job_title { get; set; }
        public virtual DbSet<personal_account> personal_account { get; set; }
        public virtual DbSet<repair_requsts> repair_requsts { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<subscriber> subscriber { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<treaty> treaty { get; set; }
        public virtual DbSet<type_of_services> type_of_services { get; set; }
    }
}
