//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> payment_sum { get; set; }
        public Nullable<double> subscriber_balance { get; set; }
        public Nullable<System.DateTime> balance_date { get; set; }
        public Nullable<double> debt { get; set; }
        public Nullable<int> subscriber { get; set; }
    
        public virtual subscribers subscribers { get; set; }
    }
}
