//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_petersburg_districts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public st_petersburg_districts()
        {
            this.subscribers_addresses = new HashSet<subscribers_addresses>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> square { get; set; }
        public Nullable<int> population { get; set; }
        public Nullable<int> metro_stations_count { get; set; }
        public string building_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscribers_addresses> subscribers_addresses { get; set; }
    }
}
