//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> job { get; set; }
        public Nullable<int> completed_app { get; set; }
    
        public virtual completed_applications completed_applications { get; set; }
        public virtual job_title job_title { get; set; }
    }
}
