//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class stations
    {
        public int id { get; set; }
        public Nullable<int> base_station { get; set; }
        public string address { get; set; }
        public string location { get; set; }
    
        public virtual base_stations base_stations { get; set; }
    }
}
