//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscribers_equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subscribers_equipment()
        {
            this.treates = new HashSet<treates>();
        }
    
        public int id { get; set; }
        public string serial_number { get; set; }
        public string name { get; set; }
        public string ports { get; set; }
        public string transfer_standart { get; set; }
        public string transfer_speed { get; set; }
        public Nullable<int> subscriber { get; set; }
    
        public virtual subscribers subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<treates> treates { get; set; }
    }
}
