//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber_tariffs
    {
        public int id { get; set; }
        public Nullable<int> subscriber { get; set; }
        public Nullable<int> tariff { get; set; }
    
        public virtual subscribers subscribers { get; set; }
        public virtual tariffs tariffs { get; set; }
    }
}
