//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class treaty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public treaty()
        {
            this.personal_account = new HashSet<personal_account>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<int> type_of_services { get; set; }
        public Nullable<int> subscriber { get; set; }
        public Nullable<System.DateTime> date_of_conclusion { get; set; }
        public Nullable<System.DateTime> date_of_end { get; set; }
        public Nullable<bool> expired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal_account> personal_account { get; set; }
        public virtual subscriber subscriber1 { get; set; }
        public virtual type_of_services type_of_services1 { get; set; }
    }
}
