//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class treates
    {
        public int id { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
        public Nullable<int> subscriber { get; set; }
        public Nullable<int> tariff { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string termination_reason { get; set; }
        public Nullable<int> equipment_serial_number { get; set; }
    
        public virtual subscribers subscribers { get; set; }
        public virtual subscribers_equipment subscribers_equipment { get; set; }
        public virtual tariffs tariffs { get; set; }
    }
}
